---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: dev-tooling-project
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/dev-tooling"
    tags:
    - projects
- object: apicurio-server
  content:
  - name: eap-7.1-imagestream
    template: "{{ inventory_dir }}/../templates/imagestream-one-tag.yml"
    params: "{{ inventory_dir }}/../params/apicurio/eap-imagestream"
    namespace: dev-tooling
    tags:
    - apicurio
  - name: apicurio-build
    template: "{{ inventory_dir }}/../templates/s2i-source-build.yml"
    params: "{{ inventory_dir }}/../params/apicurio/apicurio-image-build"
    namespace: dev-tooling
    tags:
    - apicurio